"""
routers/sessions.py — Persistent chat session CRUD.

Sessions used to live in the user's localStorage, which made them invisible
across machines and unshareable. Moving them to a Qdrant sidecar collection
unlocks two things:

  1. A user can paste /r/owner/repo/c/<sessionId> in Slack and the receiver
     reads the same conversation, no extra steps.
  2. Cross-device continuity — start a chat on a laptop, finish it on phone.

The collection is kv-shaped (no vector search): lookup by exact session_id,
list by repo. Implementation detail lives in QdrantStore — this router is
just the HTTP front door.

Routes:
  GET    /sessions?repo=owner/name    — list sessions for a repo (newest first)
  GET    /sessions/{session_id}       — fetch one session
  POST   /sessions                    — upsert (create or update)
  DELETE /sessions/{session_id}       — delete a session
"""

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field

from backend.dependencies import get_qdrant_store
from ingestion.qdrant_store import QdrantStore

router = APIRouter(prefix="/sessions", tags=["sessions"])


class SessionMessage(BaseModel):
    """One chat turn. Loose validation — frontend has the source of truth
    for shape; we just persist whatever the frontend sends so future
    additions to the message schema (new fields like `pipeline`, `model`,
    etc.) don't require backend deploys."""
    role:     str
    content:  str | None = None

    model_config = {"extra": "allow"}


class SessionPayload(BaseModel):
    """Upsert payload — same shape as the localStorage record so the
    migration step on the frontend can pipe records through unchanged.

    `id` is generated by the frontend (uuid v4 typically) and is the
    canonical key. Re-posting with the same id overwrites the previous
    payload, so a chat that grows turn by turn just upserts each time."""
    id:         str = Field(..., min_length=4, max_length=128)
    repo:       str = Field(..., min_length=3)
    title:      str = ""
    timestamp:  str
    agent_mode: bool = Field(False, alias="agentMode")
    messages:   list[SessionMessage] = []

    model_config = {"populate_by_name": True, "extra": "allow"}


@router.get("")
def list_sessions(
    store: Annotated[QdrantStore, Depends(get_qdrant_store)],
    repo:  str = Query(..., description="owner/name slug"),
):
    """Return all sessions for a repo, newest-first."""
    return {"sessions": store.list_sessions(repo)}


@router.get("/{session_id}")
def get_session(
    session_id: str,
    store:      Annotated[QdrantStore, Depends(get_qdrant_store)],
):
    """Fetch one session by id. 404 if missing — caller can fall back
    to a fresh chat (which is what the frontend already does on a bad
    session URL)."""
    s = store.get_session(session_id)
    if not s:
        raise HTTPException(status_code=404, detail="session not found")
    return s


@router.post("")
def upsert_session(
    payload: SessionPayload,
    store:   Annotated[QdrantStore, Depends(get_qdrant_store)],
):
    """Create or update a session. Same id always upserts in place —
    no separate POST/PUT split (the frontend doesn't need it and YAGNI
    says don't build it)."""
    data = payload.model_dump(by_alias=False, exclude_none=False)
    # The Pydantic alias maps agentMode→agent_mode internally; the frontend
    # storage uses agentMode, so persist with that key for round-trip clarity.
    if "agent_mode" in data:
        data["agentMode"] = data.pop("agent_mode")
    store.save_session(data)
    return {"ok": True, "id": payload.id}


@router.delete("/{session_id}")
def delete_session(
    session_id: str,
    store:      Annotated[QdrantStore, Depends(get_qdrant_store)],
):
    """Delete a session. Idempotent — non-existent ids return ok=True."""
    store.delete_session(session_id)
    return {"ok": True}


# ── Artifact provenance (debug-only inspection path) ──────────────────────
# Returns which model produced each cached artifact for a repo. Not linked
# from the UI; intended as a curl target so the project owner can audit
# cache contents (e.g. "is the nanoGPT tour using the premium model yet?").

artifacts_router = APIRouter(tags=["artifacts"])


@artifacts_router.get("/repos/{owner}/{name}/artifacts/info")
def list_artifact_info(
    owner: str,
    name:  str,
    store: Annotated[QdrantStore, Depends(get_qdrant_store)],
):
    """Return the kind / generated_by_model / generated_at of every cached
    artifact for this repo. Used to audit pre-bake runs without touching
    the live UI."""
    repo = f"{owner}/{name}"
    return {
        "repo":      repo,
        "artifacts": store.list_artifacts(repo),
    }
